name: pojo-agent ci
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  ci:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew clean suite --no-daemon
